function options = getTrainingOptions()
%GETTRAININGOPTIONS Returns trainingOptions object for object detection
options = trainingOptions('sgdm', ...
    'MiniBatchSize', 8, ...
    'InitialLearnRate', 1e-3, ...
    'MaxEpochs', 10, ...
    'VerboseFrequency', 20, ...
    'Shuffle', 'every-epoch', ...
    'Plots', 'training-progress', ...
    'Verbose', true);
end
